### ISSUE TITLE
JPNIC申請情報の入力欄の改善

### ISSUE THREAD

**Issue by kt-yamaguchi** [homenoc/dsbd-feedback#12]
・必須項目と推奨項目の明確な表示
・Org/Deptの表示の日本語化
・郵便番号について記載方式を‐アリに統一
・JPNIC Handleの文字が枠からはみ出ている問題の修正
・電話番号の書式を-アリに統一

![image](https://user-images.githubusercontent.com/19766266/160274436-b05e74dc-d986-481f-9d4f-0287e3c961ec.png)

**Comment by yoneyan** [comment]
電話番号は日本の番号のみ考えればOK

**Comment by yoneyan** [comment]
[e768c62cea5e33c5e5529fe04fab0d133023cd4d](https://github.com/homenoc/dsbd-web/commit/e768c62cea5e33c5e5529fe04fab0d133023cd4d) にて改善
