### ISSUE TITLE
希望NOCを何も選ばなかった場合、青い枠だけが表示されてしまう。

### ISSUE THREAD

**Issue by kt-yamaguchi** [homenoc/dsbd-feedback#14]
![image](https://user-images.githubusercontent.com/19766266/162788645-8ce16ea6-b073-473c-ab10-a4faeafdd6c2.png)

**Comment by kt-yamaguchi** [comment]
選択肢に「希望なし」の候補と、「希望なし」の表示が必要。

**Comment by yoneyan** [comment]
v5より申請時の希望NOC選択機能廃止のため、Close
