### ISSUE TITLE
IPトランジットユーザのアドレス表記とAS-Path表記

### ISSUE THREAD

**Issue by kt-yamaguchi** [homenoc/dsbd-feedback#16]
![image](https://user-images.githubusercontent.com/19766266/162789324-d072aa86-35f7-4052-8d97-6f7d33330111.png)
「貴団体からアドレスを割り当て」という日本語がおかしいので、「貴団体から広報するアドレス」という表現にしたい。
また、広報を許可しているAS-Path/Prefix情報を書ける欄が欲しい。

**Comment by yoneyan** [comment]
v5にてbgp_commentなどの補足フォームを追加したため、Close
