### ISSUE TITLE
[グループ情報の申請]の不具合

### ISSUE THREAD

**Issue by mino7r86** [homenoc/dsbd-feedback#18]
申請者が学生の際に入力が必要な日付を入力したところ画像のようなエラーが表示され登録が完了しませんでした。
![スクリーンショット 2022-06-14 13 31 17](https://user-images.githubusercontent.com/102952062/173493819-d4249cf6-bdcd-4698-aa79-a615ff7ae3a7.png)

**Comment by yoneyan** [comment]
v5移行時に修正済み
