### ISSUE TITLE
学生としてユーザ登録できない

### ISSUE THREAD

**Issue by kt-yamaguchi** [homenoc/dsbd-feedback#20]
フォームにて「私は学生です」にチェックを入れ、その他必要事項を記入した状態で次に進もうとすると、 [500] parsing time "2023-03-30T15:00:00.000Z": extra text: T15:00:00.000Z OK とのエラーメッセージが表示され、申請が完了しない。

**Comment by yoneyan** [comment]
<img width="1013" alt="image" src="https://user-images.githubusercontent.com/40447529/183299929-531832d8-4dea-476e-b77d-500a94ec374e.png">

**Comment by yoneyan** [comment]
v5移行時に修正済み
