### ISSUE TITLE
ログイン後 [500] error: getting membership になって何もできない

### ISSUE THREAD

**Issue by sorah** [homenoc/dsbd-feedback#23]
AS59128 の sorah です。

![](https://img.sorah.jp/x/20220816_180256_rVCuKgLSSY.png)

表題の通り何もできないです…障害かもしれませんがこちらに起票しておきます。既存チケットのやり取りを確認したかっただけで急ぎではありません。

**Comment by yoneyan** [comment]
今回の原因は、システムをv4からv5にアップグレードしたことで起きておりました。
データベース内のmemer_type値がnullにより起きていましたので、先程修正しました。

**Comment by sorah** [comment]
解消を確認しました!
