### ISSUE TITLE
no-reply@ より届くメールに charset が定義されていない

### ISSUE THREAD

**Issue by sorah** [homenoc/dsbd-feedback#24]
`Content-Type: text/plain; charset=utf-8` を差し込むだけで解決すると思います。下記のような問題があります。

- rspamd などスパムフィルタでスコア加算されてしまう
  - https://github.com/rspamd/rspamd/blob/5b2051f9f4cebb48cca0b5b7afce97e520c8006e/rules/regexp/headers.lua#L146-L154
- charset が不明となり文字化けするケースがある

**Comment by yoneyan** [comment]
いつもありがとうございますー！
解決策も含めて提示していただきまして非常に助かります。
この問題に関しては私の稼働が落ち着き次第、修正させていただきます。

**Comment by gashix2** [comment]
下記のチケットに関連コメントしていますので、共有させていただきます。
https://github.com/homenoc/dsbd-feedback/issues/9#issuecomment-2343777485
