### ISSUE TITLE
接続情報の管理画面で「DISABLE」を行った際の通知内容の問題

### ISSUE THREAD

**Issue by kt-yamaguchi** [homenoc/dsbd-feedback#25]
接続情報の管理画面で「DISABLE」を行うと、Slackに「インターネット接続: はい（IPoEによりIPv6インターネットへ接続可能） => はい（IPoEによりIPv6インターネットへ接続可能）」と通知される。

**Comment by yoneyan** [comment]
https://github.com/homenoc/dsbd-backend/issues/159 にて修正済み
