### ISSUE TITLE
Group情報申請画面の"会費についてボタン"のリンクが切れている

### ISSUE THREAD

**Issue by symysak** [homenoc/dsbd-feedback#28]
問題: Group情報申請画面の"会費についてボタン"のリンクが切れている

該当ページ: https://dashboard.homenoc.ad.jp/dashboard/add/group
場所: ↓
![image](https://user-images.githubusercontent.com/103905928/205440956-6afbe660-c605-4068-a372-19e45292d3cf.png)

特に困ってはいませんが、念のため取り急ぎご連絡させていただきます。

**Comment by symysak** [comment]
プライバシーポリシーボタンのリンクも切れているようです。

**Comment by yoneyan** [comment]
ありがとうございます。
修正します。

**Comment by yoneyan** [comment]
本Issueに対しては https://github.com/homenoc/dsbd-web/commit/4b875c14a689015cf16a1ec25edde64b419684ac にて修正しました。
ご協力いただき、ありがとうございました。
