### ISSUE TITLE
接続情報の新規新規申請画面でBGPタイプを選択できない。

### ISSUE THREAD

**Issue by kt-yamaguchi** [homenoc/dsbd-feedback#4]
サービス情報でBGPの利用を選択したユーザが次のステップとして接続申請をする際に、
BGPの経路方式（フルルートかデフォルトルートか）を選ぶメニューが表示されていない（添付画像）
これが原因により「[400] error: invalid ipv4 route template.」が表示され申請を完了することができない。
![image](https://user-images.githubusercontent.com/19766266/154373391-90d3d51e-4c30-4a38-a944-b7a6ef0c3126.png)

※ 管理者画面には表示されるようなので、ユーザ画面だけに表示されない。

**Comment by yoneyan** [comment]
https://github.com/homenoc/dsbd-web/issues/123
https://github.com/homenoc/dsbd-web-admin/issues/101
にて修正済み
