### ISSUE TITLE
接続情報の新規申請画面でStatic接続の場合でもBGP経路の選択が表示される

### ISSUE THREAD

**Issue by kt-yamaguchi** [homenoc/dsbd-feedback#5]
接続情報の新規申請画面でStatic接続の場合でもBGP経路の選択が表示される。（添付画像）
これが原因により「[400] error: invalid ipv4 route template.」が表示され申請を完了することができない。
![image](https://user-images.githubusercontent.com/19766266/156213476-78d80dac-e506-4605-9bf0-fae45ba761c7.png)

**Comment by yoneyan** [comment]
https://github.com/homenoc/dsbd-web/issues/123
https://github.com/homenoc/dsbd-web-admin/issues/101
にて修正済み
