### ISSUE TITLE
接続情報の追加でEtherIPとCrossConnectしか選べない

### ISSUE THREAD

**Issue by kt-yamaguchi** [homenoc/dsbd-feedback#6]
GRE・IP-IPが選べない
![Uploading image.png…]()

**Comment by yoneyan** [comment]
https://github.com/homenoc/dsbd-web/issues/123
https://github.com/homenoc/dsbd-web-admin/issues/101
にて修正済み

**Comment by yoneyan** [comment]
v5修正済み
