### ISSUE TITLE
チャットシステムからの自動送信メールが文字化けする

### ISSUE THREAD

**Issue by kt-yamaguchi** [homenoc/dsbd-feedback#9]
以下の申告あり、メールが文字化けしている。
```
メールクライアントにAndroidのGMailアプリを使用しているのですが、Home NOCのシステムからのメールが文字化けします。  
場合によって、WindowsのThunderbirdでも文字化けが確認できます。  
文字化けしたときの例は以下です。

UTF-8で記載されているようですが、Content-Type: charset にUTF-8の指定が無いため、文字化けが起こっているのではないかと考えています。
```

**Comment by gashix2** [comment]
Content-Typeの上に無駄な空行があるため、ヘッダではなく本文と認識されています。
※E-Mailの仕様上、最初の空行より上がヘッダ、以降が本文と認識されるため（RFC822他）

```
From:"Home NOC Operators' Group Support" <no-reply@homenoc.ad.jp>
Subject: =?utf-8?B?5pys5Lq656K66KqN44Gu44Oh44O844Or44Gr44Gk44GN44G+44GX?=
 =?utf-8?B?44Gm?=
　　　　　　　　　　　　　　　　　　　　　　　←ここに無駄な空行があるためヘッダと認識されない
Content-Type: text/plain; charset=UTF-8

ｘｘ　ｘｘ様

以下のリンクから本人確認を完了してください。
```

![issue9](https://github.com/user-attachments/assets/2268ea5d-0db0-4022-b851-fedecca1042f)


本チケットでの修正でContent-Typeが付与されたと推察しますが、お手すきで修正いただけますと幸いです

**Comment by x86taka** [comment]
@gashix2 

ご報告ありがとうございます.
こちらの[修正コミット](https://github.com/homenoc/dsbd-backend/pull/197/files)の反映確認漏れにより発生しておりました.

気がついておらず, 助かりました.

https://github.com/homenoc/dsbd-backend/pull/195
https://github.com/homenoc/dsbd-backend/pull/197

**Comment by x86taka** [comment]
https://github.com/homenoc/dsbd-backend/pull/195
https://github.com/homenoc/dsbd-backend/pull/197
